[package]
name = "travelling-salesman"
version = "0.1.0"
authors = ["0xHadfi <abdelmouminhadfi15@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ga_model"
path = "src/lib.rs"
[dependencies]
rand = "0.6.0"
